// NovaConcurrency.cpp — Nova Language Concurrency Engine Implementation
// Defines non-template logic for the ThreadPool and exposes the C-ABI
// used by the LLVM/GCC backends to interface with the concurrency engine natively.

#include "NovaConcurrency.hpp"

#include <iostream>
#include <unordered_map>

namespace nova::concurrency {

// ============================================================================
// ThreadPool Implementation
// ============================================================================

ThreadPool::ThreadPool(size_t threads) : stop(false) {
    for (size_t i = 0; i < threads; ++i) {
        workers.emplace_back([this] {
            for (;;) {
                std::function<void()> task;
                {
                    std::unique_lock<std::mutex> lock(this->queue_mutex);
                    this->condition.wait(lock, [this] {
                        return this->stop || !this->tasks.empty();
                    });
                    if (this->stop && this->tasks.empty()) {
                        return;
                    }
                    task = std::move(this->tasks.front());
                    this->tasks.pop();
                }
                // Execute the enqueued task
                task();
            }
        });
    }
}

ThreadPool::~ThreadPool() {
    shutdown();
}

void ThreadPool::shutdown() {
    {
        std::unique_lock<std::mutex> lock(queue_mutex);
        if (stop) return; // Prevent double shutdown
        stop = true;
    }
    condition.notify_all();
    for (std::thread &worker : workers) {
        if (worker.joinable()) {
            worker.join();
        }
    }
}

} // namespace nova::concurrency

// ============================================================================
// C-ABI Integration (For LLVM / GCC Backends)
// ============================================================================

// Opaque struct matching the NovaValue representation generated by backends.
extern "C" {
    struct NovaValue;
}

using namespace nova::concurrency;

// Global ThreadPool instance for the Nova Runtime (default sizing to hardware concurrency)
static std::unique_ptr<ThreadPool> g_nova_thread_pool = nullptr;
static std::once_flag g_pool_init_flag;

static void ensure_thread_pool() {
    std::call_once(g_pool_init_flag, []() {
        size_t hw_threads = std::thread::hardware_concurrency();
        if (hw_threads == 0) hw_threads = 4;
        g_nova_thread_pool = std::make_unique<ThreadPool>(hw_threads);
    });
}

extern "C" {

// ---- Threads ----

// Spawns a new OS-level thread via the Thread Pool to execute a closure/function.
// The closure argument is expected to contain the environment payload.
void nova_rt_thread_spawn(void (*func)(NovaValue*), NovaValue* arg) {
    ensure_thread_pool();
    g_nova_thread_pool->enqueue([func, arg]() {
        func(arg);
    });
}

// ---- Channels (chan<T>) ----

// Creates a typed MPMC channel. We type-erase the payload to NovaValue*.
void* nova_rt_channel_create(int64_t capacity) {
    auto* chan = new Channel<NovaValue*>(static_cast<size_t>(capacity));
    return static_cast<void*>(chan);
}

// Blocks to send a value to the channel. Returns false if closed.
bool nova_rt_channel_send(void* chan_ptr, NovaValue* val) {
    auto* chan = static_cast<Channel<NovaValue*>*>(chan_ptr);
    return chan->send(val);
}

// Blocks to receive a value. Returns NULL if the channel is empty and closed.
NovaValue* nova_rt_channel_recv(void* chan_ptr) {
    auto* chan = static_cast<Channel<NovaValue*>*>(chan_ptr);
    NovaValue* val = nullptr;
    if (chan->receive(val)) {
        return val;
    }
    return nullptr; // Indicates closed and empty
}

// Closes the channel, awakening all awaiting senders/receivers.
void nova_rt_channel_close(void* chan_ptr) {
    auto* chan = static_cast<Channel<NovaValue*>*>(chan_ptr);
    chan->close();
}

// Destroys the channel memory.
void nova_rt_channel_destroy(void* chan_ptr) {
    auto* chan = static_cast<Channel<NovaValue*>*>(chan_ptr);
    delete chan;
}

// ---- Async / Await State Machine Runner Hooks ----

// Minimalist task structure to represent suspended async state.
struct AsyncContext {
    NovaValue* state_payload;
    bool is_ready;
    std::mutex mtx;
    std::condition_variable cv;
};

// Suspends the currently running async context.
void nova_rt_async_suspend(NovaValue* ctx_ptr) {
    auto* ctx = reinterpret_cast<AsyncContext*>(ctx_ptr);
    if (!ctx) return;
    
    std::unique_lock<std::mutex> lock(ctx->mtx);
    ctx->is_ready = false;
    // Real implementation would yield to an executor. Here we just mark suspended.
}

// Resumes the async context, typically called by an I/O reactor or timer.
void nova_rt_async_resume(NovaValue* ctx_ptr) {
    auto* ctx = reinterpret_cast<AsyncContext*>(ctx_ptr);
    if (!ctx) return;
    
    std::unique_lock<std::mutex> lock(ctx->mtx);
    ctx->is_ready = true;
    ctx->cv.notify_one();
}

// Awaits an async operation. If not ready, yields the executing thread.
NovaValue* nova_rt_await(NovaValue* awaitable) {
    auto* ctx = reinterpret_cast<AsyncContext*>(awaitable);
    if (!ctx) return nullptr;

    std::unique_lock<std::mutex> lock(ctx->mtx);
    ctx->cv.wait(lock, [ctx]() { return ctx->is_ready; });
    
    return ctx->state_payload;
}

// Yield hook for generators or cooperative multi-tasking.
NovaValue* nova_rt_yield(NovaValue* value) {
    // In a full implementation, this shifts context back to the caller.
    // Stubbed to support the compiler contract.
    return value; 
}

// Initialize the global async runtime / runtime engine shutdown
void nova_rt_concurrency_shutdown() {
    if (g_nova_thread_pool) {
        g_nova_thread_pool->shutdown();
    }
}

} // extern "C"