/* Generated by Nova GCCBackend. Do not edit. */
/* Nova SSA is lowered to structured C labels/gotos with edge phi copies. */
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

typedef struct NovaValue NovaValue;

NovaValue* nova_rt_call(const char* name, NovaValue** args, int64_t argc);
NovaValue* nova_rt_alloc(int64_t size);
NovaValue* nova_rt_load(NovaValue* addr);
void nova_rt_store(NovaValue* addr, NovaValue* value);
NovaValue* nova_rt_const_int(int64_t v);
NovaValue* nova_rt_const_float(double v);
NovaValue* nova_rt_const_string(const char* v);
NovaValue* nova_rt_const_bool(bool v);
NovaValue* nova_rt_const_null(void);
int64_t nova_rt_to_int(NovaValue* v);
double nova_rt_to_float(NovaValue* v);
bool nova_rt_to_bool(NovaValue* v);
NovaValue* nova_rt_from_int(int64_t v);
NovaValue* nova_rt_from_float(double v);
NovaValue* nova_rt_from_bool(bool v);
NovaValue* nova_rt_add(NovaValue*, NovaValue*);
NovaValue* nova_rt_sub(NovaValue*, NovaValue*);
NovaValue* nova_rt_mul(NovaValue*, NovaValue*);
NovaValue* nova_rt_div(NovaValue*, NovaValue*);
NovaValue* nova_rt_mod(NovaValue*, NovaValue*);
NovaValue* nova_rt_pow(NovaValue*, NovaValue*);
NovaValue* nova_rt_eq(NovaValue*, NovaValue*);
NovaValue* nova_rt_ne(NovaValue*, NovaValue*);
NovaValue* nova_rt_lt(NovaValue*, NovaValue*);
NovaValue* nova_rt_le(NovaValue*, NovaValue*);
NovaValue* nova_rt_gt(NovaValue*, NovaValue*);
NovaValue* nova_rt_ge(NovaValue*, NovaValue*);
NovaValue* nova_rt_and(NovaValue*, NovaValue*);
NovaValue* nova_rt_or(NovaValue*, NovaValue*);
NovaValue* nova_rt_neg(NovaValue*);
NovaValue* nova_rt_not(NovaValue*);
NovaValue* nova_rt_select(NovaValue*, NovaValue*, NovaValue*);
NovaValue* nova_rt_cast(NovaValue*, const char* typeName);
NovaValue* nova_rt_index(NovaValue*, NovaValue* key);
NovaValue* nova_rt_member(NovaValue*, const char* name);
NovaValue* nova_rt_slice(NovaValue*, NovaValue*, NovaValue*, NovaValue*);
NovaValue* nova_rt_make_array(NovaValue**, int64_t count);
NovaValue* nova_rt_make_map(NovaValue**, int64_t pairCount);
NovaValue* nova_rt_make_tuple(NovaValue**, int64_t count);
bool nova_rt_error_check(NovaValue*);
NovaValue* nova_rt_await(NovaValue*);
NovaValue* nova_rt_yield(NovaValue*);
void nova_rt_async_suspend(NovaValue*);
void nova_rt_async_resume(NovaValue*);
/* Nova function declarations. Values use their ABI-preserving C type. */
void nova_fn___nova_main();

void nova_fn___nova_main() {
    NovaValue* nova_v_1 = nova_rt_const_null();
    NovaValue* nova_v_2 = nova_rt_const_null();
    NovaValue* nova_v_3 = nova_rt_const_null();
    NovaValue* nova_v_4 = nova_rt_const_null();
    NovaValue* nova_v_5 = nova_rt_const_null();
    NovaValue* nova_v_6 = nova_rt_const_null();
    NovaValue* nova_v_7 = nova_rt_const_null();
    NovaValue* nova_v_8 = nova_rt_const_null();
    NovaValue* nova_v_9 = nova_rt_const_null();
    NovaValue* nova_v_10 = nova_rt_const_null();
    NovaValue* nova_v_11 = nova_rt_const_null();
    NovaValue* nova_v_12 = nova_rt_const_null();
    bool nova_v_13 = nova_rt_to_bool(nova_rt_const_null());
    NovaValue* nova_v_14 = nova_rt_const_null();
    NovaValue* nova_v_15 = nova_rt_const_null();
    NovaValue* nova_v_16 = nova_rt_const_null();
    NovaValue* nova_v_17 = nova_rt_const_null();

nova_bb_entry_0:
    nova_v_1 = nova_rt_call("nova.symbol.load", (NovaValue*[]){nova_rt_const_string("Nova")}, 1);
    nova_v_2 = nova_rt_call("nova.call", (NovaValue*[]){nova_rt_const_string("show"), nova_v_1, nova_rt_const_string("=======================================")}, 3);
    nova_v_3 = nova_rt_call("nova.symbol.load", (NovaValue*[]){nova_rt_const_string("Nova")}, 1);
    nova_v_4 = nova_rt_call("nova.call", (NovaValue*[]){nova_rt_const_string("show"), nova_v_3, nova_rt_const_string("   Welcome to Nova Guessing Game!      ")}, 3);
    nova_v_5 = nova_rt_call("nova.symbol.load", (NovaValue*[]){nova_rt_const_string("Nova")}, 1);
    nova_v_6 = nova_rt_call("nova.call", (NovaValue*[]){nova_rt_const_string("show"), nova_v_5, nova_rt_const_string("=======================================")}, 3);
    nova_v_7 = nova_rt_call("nova.symbol.load", (NovaValue*[]){nova_rt_const_string("Nova")}, 1);
    nova_v_8 = nova_rt_call("nova.call", (NovaValue*[]){nova_rt_const_string("show"), nova_v_7, nova_rt_const_string("I have thought of a secret number.")}, 3);
    nova_v_9 = nova_rt_call("nova.symbol.load", (NovaValue*[]){nova_rt_const_string("Nova")}, 1);
    nova_v_10 = nova_rt_member(nova_v_9, "ask");
    nova_v_11 = nova_rt_call("nova.call", (NovaValue*[]){nova_rt_const_string("user"), nova_v_10, nova_rt_const_string("Enter your guess: ")}, 3);
    nova_v_12 = nova_rt_mul(nova_v_11, nova_rt_from_int(((int64_t)(1))));
    nova_v_13 = nova_rt_to_bool(nova_rt_eq(nova_v_12, nova_rt_from_int(((int64_t)(42)))));
    if (nova_v_13) {
    goto nova_bb_if_then_1_1;
    } else {
    goto nova_bb_if_else_2_2;
    }
nova_bb_if_then_1_1:
    nova_v_14 = nova_rt_call("nova.symbol.load", (NovaValue*[]){nova_rt_const_string("Nova")}, 1);
    nova_v_15 = nova_rt_call("nova.call", (NovaValue*[]){nova_rt_const_string("show"), nova_v_14, nova_rt_const_string("\xf0\x9f\x8e\x89 YOU WON! 42 is the correct answer.")}, 3);
    goto nova_bb_if_join_3_3;
nova_bb_if_else_2_2:
    nova_v_16 = nova_rt_call("nova.symbol.load", (NovaValue*[]){nova_rt_const_string("Nova")}, 1);
    nova_v_17 = nova_rt_call("nova.call", (NovaValue*[]){nova_rt_const_string("show"), nova_v_16, nova_rt_const_string("\xe2\x9d\x8c Wrong! The secret was 42.")}, 3);
    goto nova_bb_if_join_3_3;
nova_bb_if_join_3_3:
    return;
}

/* Native process entry point for GCC-produced executables. */
int main(int argc, char** argv) {
    (void)argc; (void)argv;
    nova_fn___nova_main();
    return 0;
}
